[project]
name = "satellite-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "shrub2", email = "kavaliauskas.shrub1@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "requests>=2.34.2",
]

[tool.uv]
package = false

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
